name: mangayomi
description: Free and open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi.
publish_to: 'none'
version: 0.0.67+27

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.4
  cached_network_image: ^3.3.0
  http: ^1.1.0
  riverpod_annotation: ^2.2.1
  html: ^0.15.4
  font_awesome_flutter: ^10.5.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^7.3.1
  extended_image: ^8.1.1
  photo_view: ^0.14.0
  draggable_scrollbar: ^0.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  background_downloader: ^7.11.1
  permission_handler: ^11.0.1
  flutter_inappwebview: ^5.7.2+3
  draggable_menu: ^4.4.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  share_plus: ^7.2.1 
  xpath_selector_html_parser: ^3.0.1
  desktop_webview_window: ^0.2.3
  archive: ^3.4.6
  file_picker: ^5.3.3
  path_provider: ^2.1.0
  scrollable_positioned_list: ^0.3.5
  dart_eval:
    git:
      url: https://github.com/ethanblake4/dart_eval.git
      ref: f40fb94
  json_path: ^0.6.2
  bot_toast: ^4.1.3
  flutter_web_auth_2: ^3.0.2
  numberpicker: ^2.1.2
  encrypt: ^5.0.3
  js_packer: ^0.0.5
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  crypto: ^3.0.3
  rinf: ^4.13.1
  protobuf: ^3.1.0
  cupertino_icons: ^1.0.2
  

dependency_overrides:
  analyzer: ">=5.2.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/trackers_icons/
    - assets/app_icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon-red.png"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon-red.png"