name: mangayomi
description: Free and open source manga reader multi plateform app inspired by Tachiyomi.

version: 0.0.2+5

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.5.2
  flutter_riverpod: ^2.3.6
  cached_network_image: ^3.2.3
  http: ^0.13.5
  riverpod_annotation: ^2.1.1
  html: ^0.15.2
  flutter_js: ^0.7.0
  font_awesome_flutter: ^10.1.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^7.1.2
  extended_image: ^ 8.0.2
  photo_view: ^0.14.0
  draggable_scrollbar: ^0.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  package_info_plus: ^4.0.2
  background_downloader: ^7.4.0
  permission_handler: ^10.2.0
  flutter_inappwebview: ^6.0.0-beta.24+1
  draggable_menu: ^2.0.2
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  share_plus: ^7.0.0
  xpath_selector_html_parser: ^3.0.1
  desktop_webview_window: ^0.2.0
  archive: ^3.3.7
  file_picker: ^5.3.0
  path_provider: ^2.0.15
  image: ^3.3.0
  scrollview_observer: ^1.14.0
  dart_eval: ^0.6.0
  json_path: ^0.6.0
  bot_toast: ^4.0.4
  flutter_web_auth_2: ^2.1.5
  numberpicker: ^2.1.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  # flutter_launcher_icons: ^0.13.1
  isar_generator: 3.1.0+1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
 