name: mangayomi
description: Free and open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi.
publish_to: 'none'
version: 0.0.45+18

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^10.0.0
  flutter_riverpod: ^2.4.0
  cached_network_image: ^3.2.3
  http: ^1.1.0
  riverpod_annotation: ^2.1.5
  html: ^0.15.4
  font_awesome_flutter: ^10.5.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^7.3.0
  extended_image: ^8.1.0
  photo_view: ^0.14.0
  draggable_scrollbar: ^0.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  background_downloader: ^7.10.0
  permission_handler: ^11.0.0
  flutter_inappwebview: ^5.7.2+3
  draggable_menu: ^4.1.3
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  share_plus: ^7.1.0
  xpath_selector_html_parser: ^3.0.1
  desktop_webview_window: ^0.2.3
  archive: ^3.3.9
  file_picker: ^5.3.3
  path_provider: ^2.1.0
  # image: ^4.0.17
  scrollable_positioned_list: ^0.3.5
  dart_eval: ^0.6.3
    # git:
    #   url: https://github.com/kodjodevf/dart_eval.git
    #   ref: 05c54b2
  json_path: ^0.6.2
  bot_toast: ^4.0.4
  flutter_web_auth_2: ^2.1.5
  numberpicker: ^2.1.2
  encrypt: ^5.0.1
  js_packer: ^0.0.5
  media_kit: ^1.1.8+2
  media_kit_video: ^1.2.1
  media_kit_libs_video: ^1.0.3
  crypto: ^3.0.3
  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  isar_generator: 3.1.0+1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/trackers_icons/
    - assets/app_icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon-red.png"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon-red.png"